<?php

/**
 * BaseAuthorizeNetTransaction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $trans_id
 * @property string $batch_id
 * @property timestamp $submit_time_utc
 * @property timestamp $submit_time_local
 * @property string $transaction_status
 * @property string $first_name
 * @property string $last_name
 * @property string $account_type
 * @property string $account_number
 * @property float $settle_amount
 * 
 * @method string                  getTransId()            Returns the current record's "trans_id" value
 * @method string                  getBatchId()            Returns the current record's "batch_id" value
 * @method timestamp               getSubmitTimeUtc()      Returns the current record's "submit_time_utc" value
 * @method timestamp               getSubmitTimeLocal()    Returns the current record's "submit_time_local" value
 * @method string                  getTransactionStatus()  Returns the current record's "transaction_status" value
 * @method string                  getFirstName()          Returns the current record's "first_name" value
 * @method string                  getLastName()           Returns the current record's "last_name" value
 * @method string                  getAccountType()        Returns the current record's "account_type" value
 * @method string                  getAccountNumber()      Returns the current record's "account_number" value
 * @method float                   getSettleAmount()       Returns the current record's "settle_amount" value
 * @method AuthorizeNetTransaction setTransId()            Sets the current record's "trans_id" value
 * @method AuthorizeNetTransaction setBatchId()            Sets the current record's "batch_id" value
 * @method AuthorizeNetTransaction setSubmitTimeUtc()      Sets the current record's "submit_time_utc" value
 * @method AuthorizeNetTransaction setSubmitTimeLocal()    Sets the current record's "submit_time_local" value
 * @method AuthorizeNetTransaction setTransactionStatus()  Sets the current record's "transaction_status" value
 * @method AuthorizeNetTransaction setFirstName()          Sets the current record's "first_name" value
 * @method AuthorizeNetTransaction setLastName()           Sets the current record's "last_name" value
 * @method AuthorizeNetTransaction setAccountType()        Sets the current record's "account_type" value
 * @method AuthorizeNetTransaction setAccountNumber()      Sets the current record's "account_number" value
 * @method AuthorizeNetTransaction setSettleAmount()       Sets the current record's "settle_amount" value
 * 
 * @package    payment_puller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuthorizeNetTransaction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('authorize_net_transaction');
        $this->hasColumn('trans_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('batch_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('submit_time_utc', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('submit_time_local', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('transaction_status', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('account_type', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('account_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('settle_amount', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}