<?php

/**
 * BaseVariable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $value
 * 
 * @method string   getName()  Returns the current record's "name" value
 * @method string   getValue() Returns the current record's "value" value
 * @method Variable setName()  Sets the current record's "name" value
 * @method Variable setValue() Sets the current record's "value" value
 * 
 * @package    payment_puller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseVariable extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('variable');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}