<?php

/**
 * BaseAuthorizeNetBatch
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $batch_id
 * @property timestamp $settlement_time_utc
 * @property timestamp $settlement_time_local
 * @property string $settlement_state
 * @property string $payment_method
 * 
 * @method string            getBatchId()               Returns the current record's "batch_id" value
 * @method timestamp         getSettlementTimeUtc()     Returns the current record's "settlement_time_utc" value
 * @method timestamp         getSettlementTimeLocal()   Returns the current record's "settlement_time_local" value
 * @method string            getSettlementState()       Returns the current record's "settlement_state" value
 * @method string            getPaymentMethod()         Returns the current record's "payment_method" value
 * @method AuthorizeNetBatch setBatchId()               Sets the current record's "batch_id" value
 * @method AuthorizeNetBatch setSettlementTimeUtc()     Sets the current record's "settlement_time_utc" value
 * @method AuthorizeNetBatch setSettlementTimeLocal()   Sets the current record's "settlement_time_local" value
 * @method AuthorizeNetBatch setSettlementState()       Sets the current record's "settlement_state" value
 * @method AuthorizeNetBatch setPaymentMethod()         Sets the current record's "payment_method" value
 * 
 * @package    payment_puller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAuthorizeNetBatch extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('authorize_net_batch');
        $this->hasColumn('batch_id', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('settlement_time_utc', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('settlement_time_local', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('settlement_state', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('payment_method', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}