<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2013/01/21 01:38:52
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfwidgetformdoctrinechoice' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrinegenerator' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrineformfiltergenerator' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrinecli' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrinegeneratemigrationtask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinebuilddbtask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildmodeltask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinedropdbtask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebasetask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinemigratetask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrinedataloadtask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrineinsertsqltask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinedqltask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinebuildtask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinebuildsqltask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecreatemodeltables' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinegenerateadmintask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildschematask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinebuildfilterstask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinedatadumptask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrineconnectionprofiler' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionlistener' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineroutecollection' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfformfilterdoctrine' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfwebdebugpaneldoctrine' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfvalidatordoctrineunique' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfvalidatordoctrinechoice' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfdoctrinerecord' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinepager' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrineexception' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'swift_doctrinespool' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sftesterdoctrine' => '/home/www/public/PaymentPuller/lib/vendor/symfony-1.4.20/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',

  // project
  'variableformfilter' => '/home/www/public/PaymentPuller/lib/filter/doctrine/VariableFormFilter.class.php',
  'baseformfilterdoctrine' => '/home/www/public/PaymentPuller/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'paypaltransactionformfilter' => '/home/www/public/PaymentPuller/lib/filter/doctrine/PaypalTransactionFormFilter.class.php',
  'basevariableformfilter' => '/home/www/public/PaymentPuller/lib/filter/doctrine/base/BaseVariableFormFilter.class.php',
  'basepaypaltransactionformfilter' => '/home/www/public/PaymentPuller/lib/filter/doctrine/base/BasePaypalTransactionFormFilter.class.php',
  'paypal' => '/home/www/public/PaymentPuller/lib/paypal.class.php',
  'baseform' => '/home/www/public/PaymentPuller/lib/form/BaseForm.class.php',
  'variableform' => '/home/www/public/PaymentPuller/lib/form/doctrine/VariableForm.class.php',
  'paypaltransactionform' => '/home/www/public/PaymentPuller/lib/form/doctrine/PaypalTransactionForm.class.php',
  'basevariableform' => '/home/www/public/PaymentPuller/lib/form/doctrine/base/BaseVariableForm.class.php',
  'basepaypaltransactionform' => '/home/www/public/PaymentPuller/lib/form/doctrine/base/BasePaypalTransactionForm.class.php',
  'baseformdoctrine' => '/home/www/public/PaymentPuller/lib/form/doctrine/BaseFormDoctrine.class.php',

  // project_model
  'variable' => '/home/www/public/PaymentPuller/lib/model/doctrine/Variable.class.php',
  'basepaypaltransaction' => '/home/www/public/PaymentPuller/lib/model/doctrine/base/BasePaypalTransaction.class.php',
  'basevariable' => '/home/www/public/PaymentPuller/lib/model/doctrine/base/BaseVariable.class.php',
  'paypaltransactiontable' => '/home/www/public/PaymentPuller/lib/model/doctrine/PaypalTransactionTable.class.php',
  'variabletable' => '/home/www/public/PaymentPuller/lib/model/doctrine/VariableTable.class.php',
  'paypaltransaction' => '/home/www/public/PaymentPuller/lib/model/doctrine/PaypalTransaction.class.php',

  // application
  'myuser' => '/home/www/public/PaymentPuller/apps/frontend/lib/myUser.class.php',

  // modules
);
