<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/21 00:33:32
sfConfig::add(array(
  'app_paypal_mode' => 'live',
  'app_paypal_api_username' => 'mail_api1.danifer.com',
  'app_paypal_api_password' => 'BMMV4GZNASZ4Z9LD',
  'app_paypal_api_signature' => 'Ax266oM6MA8d2bOmKDyc0pniuWVlAKijxhfyRZTzfLXwb9MaX9R.gS2A',
  'app_paypal_api_endpoint' => 'https://api-3t.paypal.com/nvp',
  'app_paypal_api_webscr' => 'https://www.paypal.com/cgi-bin/webscr',
  'app_paypal_api_version' => 51,
));
