<?php

/**
 * AuthorizeNetBatchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthorizeNetBatchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthorizeNetBatchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthorizeNetBatch');
    }
}