<?php

/**
 * Variable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    payment_puller
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Variable extends BaseVariable
{
    public static function getPaypalStart()
    {
        $result = Doctrine_Query::create()
        ->select('value')
        ->from('variable v')
        ->where('v.name = ?','paypal_start')
        ->limit(1)
        ->fetchOne();

        if (!$result) {
            
            $result = new Variable();
            $result->setName('paypal_start');
            $result->setValue(date('Y-m-d H:i:s', strtotime('2005-01-01 00:00:00')));
            $result->save();
        }

        return $result;
    }
}
