<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/01/21 00:33:28
sfConfig::add(array(
  'app_paypal_mode' => 'sandbox',
  'app_paypal_api_username' => 'seller_1227931179_per_api1.danifer.com',
  'app_paypal_api_password' => 'C2QQUXDYZF5MBSUM',
  'app_paypal_api_signature' => 'AFcWxV21C7fd0v3bYYYRCpSSRl31A9hzeS3WVDZQaM5TcMuXVvnRCGUN',
  'app_paypal_api_endpoint' => 'https://api-3t.sandbox.paypal.com/nvp',
  'app_paypal_api_webscr' => 'https://www.sandbox.paypal.com/cgi-bin/webscr',
  'app_paypal_api_version' => 51,
));
