<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/01/21 00:33:28

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=paymentpuller',
  'username' => 'mysqluser',
  'password' => 'mysqluser459534',
  'encoding' => 'utf8',
  'collate' => 'utf8_unicode_ci',
  'charset' => 'utf8',
  'name' => 'doctrine',
)),);
